#!/bin/bash

# Colores para el texto
RED='\033[0;31m'
GRN='\033[0;32m'
BLU='\033[0;34m'
NC='\033[0m' # Sin color

echo ""
echo -e "Herramientas Automáticas para MacOS"
echo ""

PS3='Por favor, elige una opción: '
options=("Bypass en Recovery" "Desactivar Notificación (SIP)" "Desactivar Notificación (Recovery)" "Verificar Inscripción MDM" "Salir")
select opt in "${options[@]}"; do
	case $opt in
	"Bypass en Recovery")
		echo -e "${GRN}Bypass en Recovery"
		
		# Verificar si el volumen de datos existe y renombrar
		if [ -d "/Volumes/Macintosh HD - Data" ]; then
   			diskutil rename "Macintosh HD - Data" "Data"
		fi

		# Crear nuevo usuario
		echo -e "${GRN}Creando nuevo usuario"
        echo -e "${BLU}Presiona Enter para pasar al siguiente paso, si no introduces nada se usará el valor predeterminado"
  		
		# Leer nombre del usuario
  		echo -e "Introduce el nombre completo del usuario (Predeterminado: MAC)"
		read realName
  		realName="${realName:=MAC}"

		# Leer nombre de usuario
    	echo -e "${BLU}Introduce el nombre de usuario ${RED}SIN ESPACIOS NI ACENTOS${GRN} (Predeterminado: MAC)"
      	read username
		username="${username:=MAC}"

		# Leer contraseña
  		echo -e "${BLU}Introduce la contraseña (Predeterminado: 1234)"
    	read passw
      	passw="${passw:=1234}"

		# Ruta del sistema DSCL
		dscl_path='/Volumes/Data/private/var/db/dslocal/nodes/Default' 
        echo -e "${GRN}Creando usuario en el sistema"

  		# Crear el usuario
    	dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username"
      	dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username" UserShell "/bin/zsh"
	    dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username" RealName "$realName"
	    dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username" UniqueID "501"
	    dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username" PrimaryGroupID "20"
		mkdir "/Volumes/Data/Users/$username"
	    dscl -f "$dscl_path" localhost -create "/Local/Default/Users/$username" NFSHomeDirectory "/Users/$username"
	    dscl -f "$dscl_path" localhost -passwd "/Local/Default/Users/$username" "$passw"
	    dscl -f "$dscl_path" localhost -append "/Local/Default/Groups/admin" GroupMembership "$username"

		# Bloquear hosts de MDM
		echo "0.0.0.0 deviceenrollment.apple.com" >> /Volumes/Macintosh\ HD/etc/hosts
		echo "0.0.0.0 mdmenrollment.apple.com" >> /Volumes/Macintosh\ HD/etc/hosts
		echo "0.0.0.0 iprofiles.apple.com" >> /Volumes/Macintosh\ HD/etc/hosts
        echo -e "${GRN}Bloqueo de hosts exitoso${NC}"

		# Remover perfiles de configuración
  		touch /Volumes/Data/private/var/db/.AppleSetupDone
        rm -rf /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigHasActivationRecord
		rm -rf /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordFound
		touch /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigProfileInstalled
		touch /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordNotFound
		echo "----------------------"
		break
		;;

	"Desactivar Notificación (SIP)")
    	echo -e "${RED}Por favor, introduce tu contraseña para continuar${NC}"
        sudo rm /var/db/ConfigurationProfiles/Settings/.cloudConfigHasActivationRecord
        sudo rm /var/db/ConfigurationProfiles/Settings/.cloudConfigRecordFound
        sudo touch /var/db/ConfigurationProfiles/Settings/.cloudConfigProfileInstalled
        sudo touch /var/db/ConfigurationProfiles/Settings/.cloudConfigRecordNotFound
        break
        ;;

	"Desactivar Notificación (Recovery)")
        rm -rf /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigHasActivationRecord
		rm -rf /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordFound
		touch /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigProfileInstalled
		touch /Volumes/Macintosh\ HD/var/db/ConfigurationProfiles/Settings/.cloudConfigRecordNotFound
        break
        ;;

	"Verificar Inscripción MDM")
		echo ""
		echo -e "${GRN}Verificando la inscripción en MDM. El éxito es error${NC}"
		echo ""
		echo -e "${RED}Por favor, introduce tu contraseña para continuar${NC}"
		echo ""
		sudo profiles show -type enrollment
		break
		;;

	"Salir")
		break
		;;

	*) 
		echo "Opción no válida $REPLY"
		;;
	esac
done

